### ISSUE TITLE
example_websocket 'WebSocket' is not defined

### ISSUE THREAD

**Issue by TheGJ** [ialex32x/unity-jsb#71] opened 2022-03-16 21:27 UTC
Hello,

I tried to open the unity example project with the sample scene configured to load the websocket example and I get :

[native] failed to load module: example_websocket 'WebSocket' is not defined

Any idea? Thanks a lot!

**Comment by ialex32x** [comment] 2022-03-19 08:23
Hi TheGJ, Thank you for reporting this issue, it's a trivial bug caused by the refactoring of register.CreateClass(), it's separated into CreateClass() and CreateGlobalClass() with different purposes. It's fixed in the last commit. Thanks again.

**Closed by ialex32x** 2022-03-19 08:23 UTC
